object Form16: TForm16
  Left = 0
  Top = 0
  BorderStyle = bsNone
  Caption = 'Form16'
  ClientHeight = 453
  ClientWidth = 682
  Color = clWhite
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  WindowState = wsMaximized
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
end
